name: Test Github Actions Secrecy

on: [pull_request]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Print secret
      run: echo {{ secrets.ACTIONS_DEPLOY_KEY }}